#! vim: set sts=4 sw=4 tw=99 et ft=python:
import os

binary = Root.Program(builder, 'srcds')

binary.sources += [
    'cvars.cpp',
    'engine.cpp',
    'fs.cpp',
    'gameevents.cpp',
    'main.cpp',
    'networkstringtable.cpp',
    'server.cpp',
    'sound.cpp',
    'spatialpartition.cpp',
    'trace.cpp',
    'voice.cpp',
]
binary.compiler.cxxincludes += [
    os.path.join(builder.sourcePath),
    os.path.join(builder.sourcePath, 'public'),
    os.path.join(builder.sourcePath, 'public', 'engine'),
    os.path.join(builder.sourcePath, 'public', 'tier1'),
    os.path.join(builder.sourcePath, 'third_party', 'amtl'),
]

if binary.compiler.like('gcc'):
    binary.compiler.linkflags += [
        '-Wl,-z,origin',
    ]
    binary.compiler.postlink += [
        Root.tier1[builder.cxx.target.arch],
        '-ldl',
        '-lpthread',
    ]
elif binary.compiler.like('msvc'):
    binary.compiler.linkflags += [
        Root.tier1[builder.cxx.target.arch],
    ]

# Transform 'tier0' => 'tier0_i486.so' or whatever funky name is needed for
# this platform. The rename map is computed in AMBuildScript.
def link_library(srcbin, destname_key):
    _, ext = os.path.splitext(srcbin.path)
    newname = Root.renames[binary.compiler.target.arch][destname_key]
    newname += ext

    output_path = os.path.join(binary.localFolder, newname)

    # Ensure the output path exists.
    builder.AddFolder(binary.localFolder)
    output = builder.AddSymlink(srcbin, output_path)

    binary.compiler.weaklinkdeps += [output]
    binary.compiler.linkflags += ['-Wl,-rpath,$ORIGIN/']
    binary.compiler.linkflags += [newname]

arch = binary.compiler.target.arch

if binary.compiler.like('msvc'):
    binary.compiler.linkflags += [
        Root.tier0[builder.cxx.target.arch],
        Root.vstdlib[builder.cxx.target.arch],
        Root.gamedll[builder.cxx.target.arch]
    ]
else:
    link_library(Root.tier0[arch], 'tier0')
    link_library(Root.vstdlib[arch], 'vstdlib')

entry = builder.Add(binary).binary
Root.srcds[binary.compiler.target.arch] = entry
